# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 schedule:
    - cron: "*/30 * * * *"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: connect
        run: |
          ftp ${{ secrets.FTP_URL }}
          ${{ secrets.FTP_USER }}
          ${{ secrets.FTP_PASS }}
          cd ./dayzps/config
          lcd ${{ github.workspace }}/dayzps/config
          ls
          quit
